repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict


-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports


-   repo: local

    hooks:
      - id: flake8
        name: flake8
        exclude: migrations/
        entry: flake8
        language: system
        types: [python]
