version: '3.8'

services:

  test_app:
    container_name: test_app
    env_file:
      - ./test.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: "--dev"
    command: pytest -vv
    networks:
      - test_network

networks:
  test_network:
    name: test_network
