version: '3.8'

services:

  tests_menu_app:
    container_name: tests_menu_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite://
    command: pytest -vv
