version: '3.8'
name: food_menu_test

services:

  test_app:
    container_name: test_app
    env_file:
      - "test.env"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: "--with test"
    command: pytest -vv
    networks:
      - test_network
    depends_on:
      test_menu_db:
        condition: service_healthy
      test_cache:
        condition: service_healthy

  test_menu_db:
    image: postgres:15.1-alpine
    container_name: test_menu_db
    expose:
      - 5432
    env_file:
      - "test.env"
    restart: on-failure
    networks:
      - test_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_cache:
    container_name: test_cache
    image: redis:latest
    expose:
      - 6379
    restart: on-failure
    env_file:
      - "test.env"
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 100


networks:
  test_network:
    external: false
