version: '3.8'
name: app

services:

  menu_app:
    container_name: menu_app
    env_file:
      - ./app.env
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "alembic upgrade head &&
             uvicorn menu_app.main:app --reload --host $${HOST} --port $${PORT}
      "
    networks:
      - web_network
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy


  db:
    container_name: db
    image: postgres:15.1-alpine
    env_file:
      - ./app.env
    expose:
      - $${DB_PORT}
    networks:
      - web_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 100


  cache:
    container_name: cache
    image: redis:latest
    expose:
      - 6379
    networks:
      - web_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 100


networks:
  web_network:
    name: web_network
