"""migrate

Revision ID: 07673f752735
Revises: 69d38a7e4df4
Create Date: 2023-01-15 16:31:18.281443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '07673f752735'
down_revision = '69d38a7e4df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
