"""migrate

Revision ID: 38170db84760
Revises: 75036cb19a15
Create Date: 2023-01-15 08:35:19.428994

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '38170db84760'
down_revision = '75036cb19a15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('dishes_count', sa.Integer(), nullable=True))
    op.add_column('submenu', sa.Column('dishes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'dishes_count')
    op.drop_column('menu', 'dishes_count')
    # ### end Alembic commands ###
