"""migrate

Revision ID: 39a6de4efae8
Revises: f9de9510ae02
Create Date: 2023-01-15 18:23:10.649765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '39a6de4efae8'
down_revision = 'f9de9510ae02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
