"""migrate

Revision ID: 5968f491c2da
Revises: 39a6de4efae8
Create Date: 2023-01-15 18:38:23.006687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5968f491c2da'
down_revision = '39a6de4efae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_menu_id_fkey', 'dish', type_='foreignkey')
    op.drop_column('dish', 'menu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dish_menu_id_fkey', 'dish', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###
