"""migrate

Revision ID: 5e030f46185a
Revises: e626b1726b89
Create Date: 2023-01-15 08:19:25.238181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5e030f46185a'
down_revision = 'e626b1726b89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
