"""migrate

Revision ID: 69d38a7e4df4
Revises: b910da6fd613
Create Date: 2023-01-15 10:37:38.268685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '69d38a7e4df4'
down_revision = 'b910da6fd613'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
