"""migrate

Revision ID: 75036cb19a15
Revises: 5e030f46185a
Create Date: 2023-01-15 08:21:06.487724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '75036cb19a15'
down_revision = '5e030f46185a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('submenus_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'submenus_count')
    # ### end Alembic commands ###
