"""migrate

Revision ID: 8c25bdca4e3d
Revises: 38170db84760
Create Date: 2023-01-15 09:43:43.170836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8c25bdca4e3d'
down_revision = '38170db84760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dish', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_column('dish', 'menu_id')
    # ### end Alembic commands ###
