"""migrate

Revision ID: 8e0cf41c5fa0
Revises: 9e2883981eac
Create Date: 2023-01-15 21:58:57.665055

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8e0cf41c5fa0'
down_revision = '9e2883981eac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
