"""migrate

Revision ID: 9e2883981eac
Revises: 5968f491c2da
Create Date: 2023-01-15 21:15:15.676193

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9e2883981eac'
down_revision = '5968f491c2da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
