"""migrate

Revision ID: b910da6fd613
Revises: 8c25bdca4e3d
Create Date: 2023-01-15 10:12:16.735673

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b910da6fd613'
down_revision = '8c25bdca4e3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
