name: tests
  # run tests
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependecies
        run: |
          pip install poetry
          poetry install
      - name: tests
        env:
          DATABASE_URL: "sqlite+aiosqlite://"
          BASE_PREFIX: "0.0.0.0:8000/api/v1/"
        run: |
          make localtest
